version: '3.8'

services:
  db:
    image: postgres:16.0
    restart: always
    container_name: nbd-postgres
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: nbd
      POSTGRES_PASSWORD: nbdpassword
    ports:
      - 5555:5432
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
